# Generated by Django 5.2 on 2026-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_sr_team',
            field=models.BooleanField(default=False, verbose_name='SR 접수 처리 팀 여부'),
        ),
    ]
