version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=False
    depends_on:
      - db

  scheduler:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=False
    depends_on:
      - db
    command: >
      sh -c "
        while true; do
          # 매시간 정각에 체크 (실제로는 cron 시간에만 실행)
          if [ $$(date +%H) -eq 9 ] && [ $$(date +%M) -eq 0 ]; then
            python manage.py check_notifications --type=due_date
          fi
          if [ $$(date +%u) -eq 5 ] && [ $$(date +%H) -eq 17 ] && [ $$(date +%M) -eq 0 ]; then
            python manage.py check_notifications --type=worklog
          fi
          sleep 60
        done
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gemini
      POSTGRES_USER: gemini
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_volume:
