# Generated by Django 5.1.6 on 2025-11-20 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='시스템명')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='시스템코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('DEV', '개발중'), ('OPER', '운영중'), ('SUSP', '중단'), ('DISC', '폐기')], default='OPER', max_length=10, verbose_name='상태')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='오픈일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_systems', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '시스템',
                'verbose_name_plural': '시스템 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='계약명')),
                ('contract_type', models.CharField(choices=[('BUILD', '구축'), ('MAINT', '유지보수'), ('LICENSE', '라이선스'), ('ETC', '기타')], max_length=20, verbose_name='계약유형')),
                ('contractor', models.CharField(blank=True, max_length=100, verbose_name='계약업체')),
                ('start_date', models.DateField(verbose_name='계약시작일')),
                ('end_date', models.DateField(verbose_name='계약종료일')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='계약금액')),
                ('content', models.TextField(blank=True, verbose_name='계약내용')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='계약서 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='assets.system', verbose_name='관련시스템')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'ordering': ['-start_date'],
            },
        ),
    ]
