# Generated by Django 5.1.6 on 2025-11-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장비명')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='시리얼번호')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='도입일')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='보증만료일')),
                ('status', models.CharField(choices=[('OPER', '운영중'), ('IDLE', '유휴'), ('REPAIR', '수리중'), ('DISC', '폐기')], default='OPER', max_length=10, verbose_name='상태')),
                ('specifications', models.TextField(blank=True, verbose_name='상세사양')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardwares', to='assets.system', verbose_name='관련시스템')),
            ],
            options={
                'verbose_name': '하드웨어',
                'verbose_name_plural': '하드웨어 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='소프트웨어명')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='버전')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('license_type', models.CharField(choices=[('PERP', '영구'), ('SUB', '구독'), ('OPEN', '오픈소스')], default='PERP', max_length=10, verbose_name='라이선스 유형')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='도입일')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='유지보수만료일')),
                ('status', models.CharField(choices=[('OPER', '운영중'), ('EXP', '만료'), ('DISC', '폐기')], default='OPER', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='assets.system', verbose_name='관련시스템')),
            ],
            options={
                'verbose_name': '소프트웨어',
                'verbose_name_plural': '소프트웨어 목록',
                'ordering': ['name'],
            },
        ),
    ]
