# Generated by Django 5.1.6 on 2025-11-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_hardware_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='system',
        ),
        migrations.RemoveField(
            model_name='software',
            name='system',
        ),
        migrations.AddField(
            model_name='hardware',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='hardwares', to='assets.system', verbose_name='관련시스템'),
        ),
        migrations.AddField(
            model_name='software',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='assets.system', verbose_name='관련시스템'),
        ),
    ]
