# Generated by Django 5.1.6 on 2025-11-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_hardware_system_remove_software_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='related_contracts',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='assets.contract', verbose_name='연관계약'),
        ),
    ]
