# Generated by Django 5.1.6 on 2025-11-21 06:41

from django.db import migrations, models


def migrate_system_to_systems(apps, schema_editor):
    """Migrate data from old system ForeignKey to new systems ManyToManyField"""
    Contract = apps.get_model('assets', 'Contract')
    for contract in Contract.objects.all():
        # Get the old system_id before it's removed
        if hasattr(contract, 'system_id') and contract.system_id:
            # Add the old system to the new systems field
            contract.systems.add(contract.system_id)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_contract_related_contracts'),
    ]

    operations = [
        # Step 1: Add new systems field (without removing old system yet)
        migrations.AddField(
            model_name='contract',
            name='systems',
            field=models.ManyToManyField(related_name='contracts', to='assets.system', verbose_name='관련시스템'),
        ),
        # Step 2: Migrate data from system to systems
        migrations.RunPython(migrate_system_to_systems, reverse_code=migrations.RunPython.noop),
        # Step 3: Now remove old system field
        migrations.RemoveField(
            model_name='contract',
            name='system',
        ),
        # Step 4: Update related_contracts to be symmetrical
        migrations.AlterField(
            model_name='contract',
            name='related_contracts',
            field=models.ManyToManyField(blank=True, to='assets.contract', verbose_name='연관계약'),
        ),
    ]
