# Generated by Django 5.1.6 on 2025-11-24 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_contract_system_contract_systems_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('CONTRACT_ADD', '계약 연결'), ('CONTRACT_REMOVE', '계약 해제'), ('HARDWARE_ADD', '하드웨어 연결'), ('HARDWARE_REMOVE', '하드웨어 해제'), ('SOFTWARE_ADD', '소프트웨어 연결'), ('SOFTWARE_REMOVE', '소프트웨어 해제')], max_length=20, verbose_name='작업')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='변경 필드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.contract', verbose_name='관련 계약')),
                ('related_hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.hardware', verbose_name='관련 하드웨어')),
                ('related_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.software', verbose_name='관련 소프트웨어')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.system', verbose_name='시스템')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '시스템 이력',
                'verbose_name_plural': '시스템 이력 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
