# Generated by Django 5.1.6 on 2025-11-26 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_systemhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제'), ('LINK_CONTRACT_ADD', '연관계약 연결'), ('LINK_CONTRACT_REMOVE', '연관계약 해제')], max_length=20, verbose_name='작업')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='변경 필드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.contract', verbose_name='계약')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_histories', to='assets.contract', verbose_name='관련 계약')),
                ('related_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.system', verbose_name='관련 시스템')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '계약 이력',
                'verbose_name_plural': '계약 이력 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제')], max_length=20, verbose_name='작업')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='변경 필드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.hardware', verbose_name='하드웨어')),
                ('related_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.system', verbose_name='관련 시스템')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '하드웨어 이력',
                'verbose_name_plural': '하드웨어 이력 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제')], max_length=20, verbose_name='작업')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='변경 필드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('related_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.system', verbose_name='관련 시스템')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.software', verbose_name='소프트웨어')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '소프트웨어 이력',
                'verbose_name_plural': '소프트웨어 이력 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
