# Generated by Django 5.1.6 on 2025-11-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_contracthistory_hardwarehistory_softwarehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthistory',
            name='action',
            field=models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제'), ('LINK_CONTRACT_ADD', '연관계약 연결'), ('LINK_CONTRACT_REMOVE', '연관계약 해제'), ('USER_COMMENT', '사용자 입력')], max_length=20, verbose_name='작업'),
        ),
        migrations.AlterField(
            model_name='hardwarehistory',
            name='action',
            field=models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제'), ('USER_COMMENT', '사용자 입력')], max_length=20, verbose_name='작업'),
        ),
        migrations.AlterField(
            model_name='softwarehistory',
            name='action',
            field=models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제'), ('USER_COMMENT', '사용자 입력')], max_length=20, verbose_name='작업'),
        ),
        migrations.AlterField(
            model_name='systemhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('CONTRACT_ADD', '계약 연결'), ('CONTRACT_REMOVE', '계약 해제'), ('HARDWARE_ADD', '하드웨어 연결'), ('HARDWARE_REMOVE', '하드웨어 해제'), ('SOFTWARE_ADD', '소프트웨어 연결'), ('SOFTWARE_REMOVE', '소프트웨어 해제'), ('USER_COMMENT', '사용자 입력')], max_length=20, verbose_name='작업'),
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.contract', verbose_name='계약')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '계약 첨부파일',
                'verbose_name_plural': '계약 첨부파일 목록',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
