# Generated by Django 5.1.6 on 2025-12-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_regularinspectionattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwarehistory',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='hardwarehistory',
            name='related_system',
        ),
        migrations.RemoveField(
            model_name='hardwarehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='softwarehistory',
            name='related_system',
        ),
        migrations.RemoveField(
            model_name='softwarehistory',
            name='software',
        ),
        migrations.RemoveField(
            model_name='softwarehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemhistory',
            name='related_contract',
        ),
        migrations.RemoveField(
            model_name='systemhistory',
            name='related_hardware',
        ),
        migrations.RemoveField(
            model_name='systemhistory',
            name='related_software',
        ),
        migrations.RemoveField(
            model_name='systemhistory',
            name='system',
        ),
        migrations.RemoveField(
            model_name='systemhistory',
            name='user',
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('SYSTEM', '시스템'), ('CONTRACT', '계약'), ('HARDWARE', '하드웨어'), ('SOFTWARE', '소프트웨어')], max_length=20, verbose_name='자산 유형')),
                ('action', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('CONTRACT_ADD', '계약 연결'), ('CONTRACT_REMOVE', '계약 해제'), ('HARDWARE_ADD', '하드웨어 연결'), ('HARDWARE_REMOVE', '하드웨어 해제'), ('SOFTWARE_ADD', '소프트웨어 연결'), ('SOFTWARE_REMOVE', '소프트웨어 해제'), ('SYSTEM_ADD', '시스템 연결'), ('SYSTEM_REMOVE', '시스템 해제'), ('LINK_CONTRACT_ADD', '연관계약 연결'), ('LINK_CONTRACT_REMOVE', '연관계약 해제'), ('USER_COMMENT', '사용자 입력'), ('REGULAR_INSPECTION', '정기점검')], max_length=20, verbose_name='작업')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='변경 필드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.contract', verbose_name='계약')),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.hardware', verbose_name='하드웨어')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_histories', to='assets.contract', verbose_name='관련 계약')),
                ('related_hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_histories', to='assets.hardware', verbose_name='관련 하드웨어')),
                ('related_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_histories', to='assets.software', verbose_name='관련 소프트웨어')),
                ('related_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_histories', to='assets.system', verbose_name='관련 시스템')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.software', verbose_name='소프트웨어')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='assets.system', verbose_name='시스템')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
            ],
            options={
                'verbose_name': '자산 이력',
                'verbose_name_plural': '자산 이력 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContractHistory',
        ),
        migrations.DeleteModel(
            name='HardwareHistory',
        ),
        migrations.DeleteModel(
            name='SoftwareHistory',
        ),
        migrations.DeleteModel(
            name='SystemHistory',
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['asset_type', '-created_at'], name='assets_asse_asset_t_39f277_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['system', '-created_at'], name='assets_asse_system__20884f_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['contract', '-created_at'], name='assets_asse_contrac_58dae7_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['hardware', '-created_at'], name='assets_asse_hardwar_04c0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['software', '-created_at'], name='assets_asse_softwar_606670_idx'),
        ),
    ]
