# Generated by Django 5.2 on 2026-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_remove_hardwarehistory_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('SAM', '일반'), ('SEC', '보안')], default='SAM', max_length=10, verbose_name='시스템구분'),
        ),
        migrations.AlterField(
            model_name='system',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='시스템코드'),
        ),
    ]
