# Generated by Django 5.1.6 on 2026-01-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_system_system_type_alter_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='inspection_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='정기점검 스케줄'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_regular_inspection',
            field=models.BooleanField(default=False, verbose_name='정기점검 대상'),
        ),
    ]
