# Generated by Django 5.1.6 on 2026-01-08 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='페이로드')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='헤더')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신일시')),
                ('processed', models.BooleanField(default=False, verbose_name='처리 여부')),
                ('external_uuid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='외부 UUID')),
            ],
            options={
                'verbose_name': '웹훅 이벤트',
                'verbose_name_plural': '웹훅 이벤트',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='소스 이름')),
                ('source_type', models.CharField(default='whatap', max_length=50, verbose_name='소스 유형')),
                ('source_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='소스 키')),
                ('secret_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='비밀 토큰')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '웹훅 소스',
                'verbose_name_plural': '웹훅 소스',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='상태')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('fatal', 'Fatal')], default='warning', max_length=20, verbose_name='심각도')),
                ('fingerprint', models.CharField(max_length=255, unique=True, verbose_name='지문(Dedupe Key)')),
                ('projectName', models.CharField(blank=True, max_length=255, verbose_name='프로젝트명')),
                ('oname', models.CharField(blank=True, max_length=255, verbose_name='대상 이름')),
                ('metricName', models.CharField(blank=True, max_length=255, verbose_name='메트릭명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결일시')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hooks.webhooksource', verbose_name='소스')),
            ],
            options={
                'verbose_name': '인시던트',
                'verbose_name_plural': '인시던트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='이벤트 유형')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hooks.incident', verbose_name='인시던트')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('raw_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hooks.webhookevent', verbose_name='원본 이벤트')),
            ],
            options={
                'verbose_name': '인시던트 이벤트',
                'verbose_name_plural': '인시던트 이벤트',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hooks.webhooksource', verbose_name='소스'),
        ),
    ]
