# Generated by Django 4.2.11 on 2025-07-07 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_ko', models.CharField(blank=True, max_length=10, verbose_name='성')),
                ('first_name_ko', models.CharField(blank=True, max_length=20, verbose_name='이름')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='부서')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='직급')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
