# Generated by Django 5.1.6 on 2025-07-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_role',
            field=models.CharField(blank=True, choices=[('member', '멤버'), ('leader', '팀장'), ('admin', '관리자')], default='member', max_length=20, verbose_name='팀 내 역할'),
        ),
    ]
