# Generated by Django 5.1.6 on 2025-08-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_is_first_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team_role',
        ),
    ]
