# Generated by Django 5.1.6 on 2025-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_role',
            field=models.CharField(blank=True, choices=[('member', '팀원'), ('leader', '팀장'), ('admin', '관리자')], default='member', max_length=20, verbose_name='팀 내 역할'),
        ),
    ]
