# Generated by Django 5.1.6 on 2025-09-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_default_display_order'),
        ('accounts', '0006_userprofile_team_role'),
    ]

    operations = [
    ]
