# Generated by Django 5.1.6 on 2025-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicerequest_servicerelease_serviceinspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='req_module',
            field=models.TextField(blank=True, null=True, verbose_name='요청모듈'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_system',
            field=models.TextField(blank=True, null=True, verbose_name='요청시스템'),
        ),
    ]
