# Generated by Django 5.1.6 on 2025-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_add_commoncode_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formelement',
            options={'ordering': ['dataset', 'order']},
        ),
        migrations.AddField(
            model_name='commoncode',
            name='seperator',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='구분자'),
        ),
        migrations.AlterField(
            model_name='commoncode',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리명'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('N', '신규요청'), ('A', '요청접수'), ('P', '처리중'), ('G', '처리완료'), ('D', '처리불가')], default='N', max_length=1),
        ),
    ]
