# Generated by Django 5.1.6 on 2025-11-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_formelement_options_commoncode_seperator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoncode',
            old_name='seperator',
            new_name='separator',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('N', '서비스 생성'), ('A', '요청접수'), ('P', '처리중'), ('G', '처리완료'), ('D', '처리불가')], default='N', max_length=1),
        ),
    ]
