# Generated by Django 5.1.6 on 2025-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_rename_seperator_commoncode_separator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='complete_content',
            field=models.TextField(blank=True, null=True, verbose_name='처리결과'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='rcv_opinion',
            field=models.TextField(blank=True, null=True, verbose_name='담당부서의견'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='처리결과'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_depart',
            field=models.TextField(blank=True, null=True, verbose_name='요청부서'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_details',
            field=models.TextField(blank=True, null=True, verbose_name='요청내용'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_email',
            field=models.TextField(blank=True, null=True, verbose_name='요청자 email'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_name',
            field=models.TextField(blank=True, null=True, verbose_name='요청자'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='req_reason',
            field=models.TextField(blank=True, null=True, verbose_name='요청사유'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='split_msg',
            field=models.TextField(blank=True, null=True, verbose_name='분할메시지'),
        ),
    ]
