# Generated by Django 5.2 on 2026-02-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_servicerequest_complete_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestattachment',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='service.servicerequeststep'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('N', '서비스 생성'), ('A', '승인 대기'), ('P', '처리중'), ('G', '처리완료'), ('D', '처리불가')], default='N', max_length=1),
        ),
    ]
