# Generated by Django 5.2 on 2026-02-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_servicerequestattachment_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestattachment',
            name='file_type',
            field=models.CharField(choices=[('REQ', '요청'), ('RCV', '접수'), ('STEP', '진행')], default='REQ', max_length=4),
        ),
    ]
