# Generated by Django 4.2.11 on 2025-07-09 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='teams.team', verbose_name='대상 팀'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('year', 'week_number', 'team')},
        ),
        migrations.CreateModel(
            name='TeamWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('week_number', models.IntegerField(verbose_name='주차')),
                ('title', models.CharField(max_length=200, verbose_name='리포트 제목')),
                ('summary', models.TextField(blank=True, verbose_name='주간 요약')),
                ('achievements', models.TextField(blank=True, verbose_name='주요 성과')),
                ('issues', models.TextField(blank=True, verbose_name='이슈 및 문제점')),
                ('next_week_plan', models.TextField(blank=True, verbose_name='다음 주 계획')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_team_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_weekly_reports', to='teams.team')),
            ],
            options={
                'ordering': ['-year', '-week_number'],
                'unique_together': {('team', 'year', 'week_number')},
            },
        ),
    ]
