# Generated by Django 5.1.6 on 2025-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_weeklyreport_unique_together_weeklyreport_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='입력마감 여부'),
        ),
    ]
