# Generated by Django 5.1.6 on 2025-11-17 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_weeklyreportpersonalcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('week_number', models.IntegerField(verbose_name='주차')),
                ('review_content', models.JSONField(verbose_name='AI 리뷰 내용')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='알림 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='리뷰 대상자')),
            ],
            options={
                'verbose_name': 'AI 리뷰 결과',
                'verbose_name_plural': 'AI 리뷰 결과 목록',
                'ordering': ['-year', '-week_number', 'user'],
                'unique_together': {('user', 'year', 'week_number')},
            },
        ),
    ]
