# Generated by Django 5.1.6 on 2025-12-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportreview'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerformanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True, verbose_name='분석 기준일')),
                ('start_week', models.CharField(max_length=10, verbose_name='분석 시작 주차')),
                ('end_week', models.CharField(max_length=10, verbose_name='분석 종료 주차')),
                ('analysis_data', models.JSONField(verbose_name='분석 결과 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analyses', to='teams.team', verbose_name='팀')),
            ],
            options={
                'verbose_name': '팀 성과 분석 리포트',
                'verbose_name_plural': '팀 성과 분석 리포트 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
