# Generated by Django 5.1.6 on 2026-02-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_teamperformanceanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamWeeklyReport',
        ),
    ]
