# Generated by Django 5.1.6 on 2025-07-18 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateField()),
                ('infra_confirmed', models.BooleanField(default=False)),
                ('ops_confirmed', models.BooleanField(default=False)),
                ('infra_status', models.CharField(choices=[('정상', '정상'), ('이상', '이상')], default='정상', max_length=10)),
                ('infra_remarks', models.TextField(blank=True)),
                ('ops_status', models.CharField(choices=[('정상', '정상'), ('이상', '이상')], default='정상', max_length=10)),
                ('ops_remarks', models.TextField(blank=True)),
                ('error_status', models.CharField(choices=[('정상', '정상'), ('이상', '이상')], default='정상', max_length=10)),
                ('error_remarks', models.TextField(blank=True)),
                ('etc_status', models.CharField(choices=[('정상', '정상'), ('이상', '이상')], default='정상', max_length=10)),
                ('etc_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='monitoring_attachments/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='monitor.monitoringrecord')),
            ],
        ),
    ]
