# Generated by Django 5.1.6 on 2025-07-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='has_trouble',
            field=models.BooleanField(default=False, verbose_name='문제'),
        ),
        migrations.AddField(
            model_name='subcategoryentry',
            name='has_trouble',
            field=models.BooleanField(default=False, verbose_name='문제'),
        ),
    ]
