# Generated by Django 5.1.6 on 2025-07-18 08:53

import django.db.models.deletion
import monitor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('monitoring_result', models.TextField(blank=True)),
                ('monitoring_yn', models.BooleanField(default=False, verbose_name='점검완료')),
                ('monitoring_created_at', models.DateTimeField(blank=True, null=True)),
                ('sap_backup_result', models.TextField(blank=True)),
                ('sap_backup_yn', models.BooleanField(default=False, verbose_name='점검완료')),
                ('sap_backup_created_at', models.DateTimeField(blank=True, null=True)),
                ('room_backup_result', models.TextField(blank=True)),
                ('room_backup_yn', models.BooleanField(default=False, verbose_name='점검완료')),
                ('room_backup_created_at', models.DateTimeField(blank=True, null=True)),
                ('cloud_backup_result', models.TextField(blank=True)),
                ('cloud_backup_yn', models.BooleanField(default=False, verbose_name='점검완료')),
                ('cloud_backup_created_at', models.DateTimeField(blank=True, null=True)),
                ('offsite_backup_result', models.TextField(blank=True)),
                ('offsite_backup_yn', models.BooleanField(default=False, verbose_name='점검완료')),
                ('offsite_backup_created_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('cloud_backup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_backup_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('duty_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('monitoring_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('offsite_backup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offsite_backup_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('room_backup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_backup_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('sap_backup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_backup_operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=monitor.models.operation_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='monitor.operationlog')),
            ],
        ),
    ]
