# Generated by Django 5.1.6 on 2025-11-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_logentry_has_trouble_subcategoryentry_has_trouble'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationlog',
            options={'ordering': ['-date'], 'verbose_name': '시스템점검일지', 'verbose_name_plural': '시스템점검일지'},
        ),
    ]
