# Generated by Django 5.1.6 on 2025-07-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_operationlog_operationlogattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringrecordattachment',
            name='record',
        ),
        migrations.DeleteModel(
            name='MonitoringRecord',
        ),
        migrations.DeleteModel(
            name='MonitoringRecordAttachment',
        ),
    ]
