# Generated by Django 5.2 on 2026-02-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_operationlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlogattachment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='monitor.logcategory'),
        ),
    ]
