# Generated by Django 5.1.6 on 2025-07-07 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('week_number', models.IntegerField(verbose_name='주차')),
                ('this_week_content', models.TextField(verbose_name='이번 주 내용')),
                ('next_week_content', models.TextField(verbose_name='다음 주 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-week_number'],
                'unique_together': {('author', 'year', 'week_number')},
            },
        ),
    ]
