# Generated by Django 5.1.6 on 2025-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='next_week_content',
            field=models.TextField(blank=True, verbose_name='다음 주 내용'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='this_week_content',
            field=models.TextField(blank=True, verbose_name='이번 주 내용'),
        ),
    ]
