# Generated by Django 4.2.11 on 2025-07-07 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklog', '0002_alter_worklog_next_week_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='worklog_files/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='worklog.worklog')),
            ],
        ),
        migrations.CreateModel(
            name='WorklogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='worklog.worklog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
