# Generated by Django 4.2.11 on 2025-07-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_category_task_assigned_to_task_description_and_more'),
        ('worklog', '0004_delete_worklogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='next_week_content',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='this_week_content',
        ),
        migrations.AddField(
            model_name='worklog',
            name='next_week_plan',
            field=models.TextField(blank=True, verbose_name='다음 주 계획'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='this_week_work',
            field=models.TextField(blank=True, verbose_name='이번 주 수행 업무'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WorklogTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', '계획됨'), ('in_progress', '진행중'), ('completed', '완료'), ('postponed', '연기'), ('cancelled', '취소')], default='planned', max_length=20, verbose_name='상태')),
                ('progress', models.IntegerField(default=0, help_text='0-100 사이의 값', verbose_name='진행률')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('time_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='소요 시간(시간)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_entries', to='task.task')),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_tasks', to='worklog.worklog')),
            ],
            options={
                'ordering': ['task__priority', 'task__title'],
                'unique_together': {('worklog', 'task')},
            },
        ),
    ]
