# Generated by Django 4.2.11 on 2025-09-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0005_remove_worklog_next_week_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['display_order', 'author__profile__last_name_ko', 'author__username']},
        ),
        migrations.AddField(
            model_name='worklog',
            name='display_order',
            field=models.IntegerField(default=0, help_text='주간보고서에서의 표시 순서 (낮은 숫자가 먼저 표시)', verbose_name='표시 순서'),
        ),
    ]
