# Generated by Django 5.2 on 2026-02-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0006_alter_worklog_options_worklog_display_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorklogTask',
        ),
    ]
