# Generated by Django 5.1.6 on 2025-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='진척율'),
        ),
    ]
