# Generated by Django 4.2.11 on 2025-09-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/', verbose_name='첨부파일'),
        ),
    ]
