# Generated by Django 5.1.6 on 2026-01-19 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_system_system_type_alter_system_code'),
        ('task', '0006_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='assets.system', verbose_name='시스템'),
        ),
    ]
