# Generated by Django 5.1.6 on 2026-01-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='system',
        ),
    ]
