# Generated by Django 5.1.6 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_remove_task_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_key_task",
            field=models.BooleanField(default=False, verbose_name="Key task"),
        ),
    ]
